server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/byte-bites-restaurant
    username: postgres
    password: 3737
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ByteBitesRestaurantApp

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
